sudo: false
language: python
cache: true
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
env:
  matrix:
    - TOXENV=py26-django14
    - TOXENV=py27-django14
    - TOXENV=py26-django15
    - TOXENV=py26-django16
    - TOXENV=py27-django15
    - TOXENV=py27-django16
    - TOXENV=py32-django15
    - TOXENV=py32-django16
    - TOXENV=py33-django15
    - TOXENV=py33-django16
    - TOXENV=py27-django17
    - TOXENV=py27-django18
    - TOXENV=py32-django17
    - TOXENV=py32-django18
    - TOXENV=py33-django17
    - TOXENV=py33-django18
    - TOXENV=py34-django17
    - TOXENV=py34-django18
    - TOXENV=py27-django19
    - TOXENV=py27-django110
    - TOXENV=py34-django19
    - TOXENV=py34-django110
    - TOXENV=py35-django19
    - TOXENV=py35-django110
    - TOXENV=py27-django111
    - TOXENV=py34-django111
    - TOXENV=py35-django111
    - TOXENV=py36-django111
install:
  - pip install tox
script:
  - tox -e ${TOXENV}
