sudo: false
language: python
cache: true
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
matrix:
  include:
    - python: '2.6'
      env:
        - DJANGO=django14
        - DJANGO=django15
        - DJANGO=django16
    - python: '2.7'
      env:
        - DJANGO=django14
        - DJANGO=django15
        - DJANGO=django16
        - DJANGO=django17
        - DJANGO=django18
        - DJANGO=django19
        - DJANGO=django110
        - DJANGO=django111
    - python: '3.2'
      env:
        - DJANGO=django15
        - DJANGO=django16
        - DJANGO=django17
        - DJANGO=django18
    - python: '3.3'
      env:
        - DJANGO=django15
        - DJANGO=django16
        - DJANGO=django17
        - DJANGO=django18
    - python: '3.4'
      env:
        - DJANGO=django19
        - DJANGO=django110
        - DJANGO=django111
    - python: '3.5'
      env:
        - DJANGO=django19
        - DJANGO=django110
        - DJANGO=django111
    - python: '2.7'
      env:
        - DJANGO=django111
install:
  - pip install tox
script:
  - tox -e ${TOXENV}
